"""Generate frontend/src/Keys.scala from the sv table in I18n.scala.

Call sites use K.someKey rather than "someKey", so deleting a translation is a
compile error instead of something a regex in verify.py has to notice. That
check was wrong twice - once matching only t("...") and so missing half the
keys, once intersecting candidates with the key set and so reporting nothing at
all - which is the argument for letting the compiler do it.
"""
import re

SRC = "frontend/src/I18n.scala"
OUT = "frontend/src/Keys.scala"

i18n = open(SRC, encoding="utf-8").read()
m = re.search(r"val sv: Map\[String, String\] = Map\((.*?)\n  \)", i18n, re.S)
if not m:
    raise SystemExit(f"{SRC}: could not find the sv table")
keys = sorted(set(re.findall(r'"([A-Za-z0-9_]+)"\s*->', m.group(1))))
if not keys:
    raise SystemExit(f"{SRC}: sv table parsed as empty")

body = "\n".join(f'  val {k}: String = "{k}"' for k in keys)
open(OUT, "w", encoding="utf-8").write(f'''package skog

/** Translation keys as named constants.
  *
  * GENERATED by scripts/gen_keys.py from the sv table in I18n.scala - do not
  * edit by hand. Referencing keys through K means a deleted translation fails
  * to compile, rather than reaching the page as literal key text and relying on
  * a regex in verify.py to catch it.
  */
object K:
{body}
''')
print(f"{OUT}: {len(keys)} keys")
